# Generated by Django 6.0.3 on 2026-04-16 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabonliquido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 4, 15, 21, 13, 50, 419361)),
            preserve_default=False,
        ),
    ]
